In [99]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import yfinance as yf
import plotly.express as px
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [100]:
# tickers = ['JPM', 'MS', 'BAC']
# start_date = '2024-01-01'
# end_date = '2025-01-01'

# data = yf.download(tickers, start = start_date, end = end_date)['Close']
# data

In [101]:
data = pd.read_excel('Indian_Stocks_18042026.xlsx')

In [102]:
data.head(10)

        Date        HDB        IBN  RELIANCE.NS     SBIN.NS       TCS.NS
0 2024-01-01        NaN        NaN  1285.609619  618.355835  3549.363037
1 2024-01-02  32.523109  23.067957  1296.255859  616.523926  3523.379150
2 2024-01-03  32.176502  23.363070  1282.160156  620.380554  3438.209961
3 2024-01-04  32.352242  23.412254  1288.786011  619.705627  3414.973389
4 2024-01-05  32.010513  23.697529  1294.270508  618.934326  3481.189941
5 2024-01-08  32.181381  23.481115  1284.170288  604.520325  3425.683838
6 2024-01-09  31.644371  23.136816  1280.770508  602.977722  3436.486816
7 2024-01-10  31.903112  23.569647  1315.314819  599.458557  3458.046875
8 2024-01-11  31.917757  23.569647  1349.908813  597.964172  3479.001465
9 2024-01-12  32.015400  23.677856  1360.654175  610.883667  3616.138916

In [103]:
## Vizualing the stocks Data

px.line(data,x=data['Date'],y=data['HDB'],title='CLosing Price of HDFC Bank')

In [104]:
px.line(data,x=data['Date'],y=data['SBIN.NS'],title='CLosing Price of State Bank of India')

In [118]:
px.line(data,x=data.index,y=data['TCS.NS'],title='CLosing Price of Tata Consultancy Services')

In [119]:
px.line(data, title = 'Closing Price of All Stocks').show()

In [120]:
data.head(2)

                  HDB        IBN  RELIANCE.NS     SBIN.NS       TCS.NS
Date
2024-01-01        NaN        NaN  1285.609619  618.355835  3549.363037
2024-01-02  32.523109  23.067957  1296.255859  616.523926  3523.379150

In [111]:
data['Date'] = pd.to_datetime(data['Date'],errors='coerce')

In [112]:
data.set_index('Date', inplace=True)

In [121]:
# Calculating SImple Returns
simple_returns = data.pct_change()
simple_returns = simple_returns.dropna()
simple_returns.head(5)

C:\Users\omman\AppData\Local\Temp\ipykernel_468\3620623623.py:2: FutureWarning:

The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.

                 HDB       IBN  RELIANCE.NS   SBIN.NS    TCS.NS
Date
2024-01-03 -0.010657  0.012793    -0.010874  0.006255 -0.024173
2024-01-04  0.005462  0.002105     0.005168 -0.001088 -0.006758
2024-01-05 -0.010563  0.012185     0.004256 -0.001245  0.019390
2024-01-08  0.005338 -0.009132    -0.007804 -0.023288 -0.015945
2024-01-09 -0.016687 -0.014663    -0.002647 -0.002552  0.003154

In [122]:
# Calculating Log Returns
log_returns  = np.log(data/data.shift(1))
log_returns = log_returns.dropna()
log_returns.head(5)

                 HDB       IBN  RELIANCE.NS   SBIN.NS    TCS.NS
Date
2024-01-03 -0.010714  0.012712    -0.010934  0.006236 -0.024470
2024-01-04  0.005447  0.002103     0.005154 -0.001089 -0.006781
2024-01-05 -0.010619  0.012111     0.004247 -0.001245  0.019204
2024-01-08  0.005324 -0.009174    -0.007834 -0.023564 -0.016073
2024-01-09 -0.016828 -0.014771    -0.002651 -0.002555  0.003149

In [124]:
# Calculating Portfolio Returns (Rp = w1r1 + w2r2 + w3r3) => [w1 w2 w3][r1 r2 r3]
weights = np.array([1/10, 1/10, 2/10,2/10,4/10])
portfolio_simple_returns = simple_returns.dot(weights)
portfolio_simple_returns.head(5)

Date
2024-01-03   -0.010379
2024-01-04   -0.001131
2024-01-05    0.008520
2024-01-08   -0.012976
2024-01-09   -0.002913
dtype: float64

In [125]:
weights = np.array([1/10, 1/10, 2/10,2/10,4/10])
portfolio_log_returns = log_returns.dot(weights)
portfolio_log_returns.head(5)

Date
2024-01-03   -0.010528
2024-01-04   -0.001144
2024-01-05    0.008431
2024-01-08   -0.013094
2024-01-09   -0.002942
dtype: float64

In [126]:
## Calculating Annualized Return using Simple Returns => (1+Avg of Simple Return)**252 -1
annualized_simple_returns = (1 + portfolio_simple_returns.mean())**252 -1
annualized_simple_returns

0.08684312337342948

In [127]:
## Calculating Annualized Log Return
annualized_log_returns = (portfolio_log_returns.mean() * 252)
annualized_log_returns

0.09251497190480013

In [128]:
## calculating Volatility
daily_volatility = np.std(portfolio_simple_returns)
annual_volatility = daily_volatility * np.sqrt(252)
annual_volatility

0.14288166078780964

In [50]:
# #Calculating Alpha & Beta Downloading S&P  500
# start_date = '2024-01-01'
# end_date = '2025-01-01'
# benchmark = yf.download('^GSPC', start=start_date,end=end_date)['Close']

In [129]:
benchmark = pd.read_excel('Indian_Benchmark_Data_18042026.xlsx')

In [130]:
benchmark.set_index('Date', inplace=True)

In [131]:
benchmark.head(5)

                   ^NSEI
Date
2024-01-01  21741.900391
2024-01-02  21665.800781
2024-01-03  21517.349609
2024-01-04  21658.599609
2024-01-05  21710.800781

In [132]:
benchmark = benchmark.pct_change()

In [133]:
benchmark = benchmark.dropna()

In [134]:
benchmark.head(5)

               ^NSEI
Date
2024-01-02 -0.003500
2024-01-03 -0.006852
2024-01-04  0.006564
2024-01-05  0.002410
2024-01-08 -0.009111

In [137]:
# Calculate Beta => beta = Covariance(Rp,Rm)/Variance(Rm)

# Converting Data Frame to a Numpy Array
combined = pd.concat(
    [portfolio_simple_returns, benchmark],
    axis=1
).dropna()

# Rename for clarity
combined.columns = ['portfolio', 'benchmark']

portfolio_returns = combined['portfolio']
benchmark_returns = combined['benchmark']

cov_matrix = np.cov(portfolio_returns, benchmark_returns)
cov_matrix

array([[8.51829157e-05, 6.36215697e-05],
       [6.36215697e-05, 6.69592301e-05]])

In [139]:
beta = cov_matrix[0][1]/cov_matrix[1][1]
beta
# """
# beta of 0.89 indicates that suppose a market goes up by 10% then our portfolio will go up by 10 * 0.89 i.e 8.9%
# also indicates as beta < 1 it is less volatile as compared to market
# """

0.9501538416510723

In [140]:
# Calculating Alpha
risk_free_rate = 0.07
alpha = (np.mean(portfolio_simple_returns) - risk_free_rate/252) - beta * (np.mean(benchmark_returns) - risk_free_rate/252)
alpha = alpha * 252
alpha

-0.019220267883373162

In [141]:
# calculating sortino ratio
negative_returns = portfolio_simple_returns[portfolio_simple_returns < 0]
downside_deviation = np.std(negative_returns)
downside_deviation = downside_deviation * np.sqrt(252)
downside_deviation

0.09950797932272012

In [142]:
sharpe_ratio = (annualized_simple_returns - risk_free_rate)/annual_volatility
sharpe_ratio

0.11788163211822415

In [87]:
"""
Sharpe ratio of 1.64 indicates that for every unit of risk taken psortfolio is generating 1.64 units of excess ratio
"""

'\nSharpe ratio of 1.64 indicates that for every unit of risk taken psortfolio is generating 1.64 units of excess ratio\n'

In [143]:
sortino_ratio = (annualized_simple_returns - risk_free_rate)/downside_deviation
sortino_ratio

0.16926404784891225

In [144]:
# Max Drawdown  = Cummulattive Return

cummulative_simple_returns = (1 + portfolio_simple_returns).cumprod()
max_drawdown = ((cummulative_simple_returns.cummax() - cummulative_simple_returns) / cummulative_simple_returns.cummax()).max()
max_drawdown

0.16560323878846772

In [145]:
calmar_ratio = annualized_simple_returns/max_drawdown
calmar_ratio

0.5244047399601768

In [146]:
treynor_ratio = (annualized_simple_returns - risk_free_rate)/beta
treynor_ratio

0.017726732909021714

In [147]:
len(data)

520

In [148]:
portfolio_value = 1000000
var_90 = np.percentile(portfolio_simple_returns, 10) * portfolio_value
var_95 = np.percentile(portfolio_simple_returns, 5) * portfolio_value
var_99 = np.percentile(portfolio_simple_returns, 1) * portfolio_value
var_99

-19136.456554831067

In [149]:
var_90

-8850.244011741594

In [150]:
var_95

-14143.055282853073

In [151]:
c_var = portfolio_simple_returns[portfolio_simple_returns <= np.percentile(portfolio_simple_returns, 5)].mean()
c_var = c_var * portfolio_value
c_var

-19823.03785959512